import { test, expect } from '@playwright/test';

test('quiet studio keeps tools folded and selection does not open note editor', async ({ page }) => {
  await page.goto('/');
  await page.getByRole('button', { name: '＋ New demo', exact: true }).click();
  await expect(page.locator('h1 .inline-name')).toHaveText(/Untitled \d+/);
  await expect(page.getByLabel('Piano roll')).not.toBeVisible();
  await expect(page.getByRole('region', { name: 'AI run monitor' })).not.toBeVisible();
  await expect(page.getByRole('button', { name: '＋ New song', exact: true })).not.toBeVisible();
  const lanes = page.locator('.lanes');
  const lanesBox = await lanes.boundingBox();
  await lanes.click({ position: { x: lanesBox!.width * 0.08, y: 58 } });
  await expect(page.locator('.scope-inline code')).toContainText('Lead');
  await lanes.click({ position: { x: lanesBox!.width * 0.08, y: 58 } });
  await expect(page.locator('.scope-inline code')).toHaveText('Whole song');
  await page.getByRole('button', { name: 'Instrument for Lead', exact: true }).click();
  await expect(page.getByLabel('Piano roll')).not.toBeVisible();
  await expect(page.locator('.topbar-companion')).toBeVisible();
  await page.screenshot({ path: 'test-results/retro-desktop.png', fullPage: true });
  await expect(page.getByLabel('Snap')).not.toBeVisible();
  await page.locator('.note-drawer > summary').click();
  await expect(page.getByLabel('Snap')).toBeVisible();
  await expect(page.getByLabel('Piano roll')).toBeVisible();
  await page.locator('.note-drawer > summary').click();
  await expect(page.getByLabel('Snap')).not.toBeVisible();
  await expect(page.getByLabel('Piano roll')).not.toBeVisible();
  await page.setViewportSize({ width: 390, height: 844 });
  await page.screenshot({ path: 'test-results/retro-mobile.png', fullPage: true });
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true);
});
